package CPP.Absyn; // Java Package generated by the BNF Converter.

public class Type_bool  extends Type {
  public Type_bool() { } //빈 생성자

  public <R,A> R accept(CPP.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }
  //accept를 통해서 visit를 리턴??

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.Type_bool) {
      return true;
    }
    return false;
  }

  public int hashCode() { //이건 어디쓰는거지...
    return 37;
  }


}
